apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production
nameSuffix: -production

resources:
  - ../../base/web
  - ingress.yaml

images:
  - name: web

labels:
  - includeSelectors: true
    pairs:
      environment: production
